### ISSUE TITLE
startup.sh doesn't work

### ISSUE THREAD

**Issue by ghost** [NoTranslation/Conky-Minimalism#8]
when i do "bash startup.sh), it shows this. _conky: cannot open /home/user/.conky/minimalism/MangoRC: File o directory non esistente_ . I have downloaded the file and extract it but there isn't MangoRC

**Comment by amoghnath** [comment]
@Sassolinoh you need to rename the folder to Conky-Minimalism and the MangoRC file to minimalismRC, there are clear instructions in the README file for you to change the file names to customize
